/* Embedded PPG heart-rate estimator — ARM Cortex-M3 (QEMU lm3s6965evb).
 *
 * Pipeline (fixed-point, Q15):  PPG samples -> band-pass FIR -> peak detection -> HR.
 * The test vector + FIR coefficients + the float reference HR are generated by
 * src/reference.py into generated/ppg_data.h. Output goes out via semihosting and
 * is checked against the Python golden reference by src/validate.py.
 */
#include <stdint.h>
#include "semihost.h"
#include "dsp_fixed.h"
#include "generated/ppg_data.h"   /* PPG_FS, PPG_N, ppg_q15[], FIR_NTAPS, fir_q15_coef[], REF_HR_X100 */

static int32_t filt[PPG_N];       /* filtered signal (.bss in SRAM) */
static int peak_idx[256];         /* up-to-256 peak indices per window */

int main(void) {
    int L = fir_q15(ppg_q15, PPG_N, fir_q15_coef, FIR_NTAPS, filt);
    int refractory = REFRACTORY_SAMPLES;             /* single source of truth: src/reference.py */
    int peaks = detect_peaks(filt, L, refractory, peak_idx, 256);

    /* HR from median inter-peak interval (robust to occasional missed/spurious peaks). */
    uint32_t hr_x100 = hr_x100_from_peaks(peak_idx, peaks, PPG_FS);

    sh_write0("PPG embedded HR estimator (Q15 FIR, Cortex-M3 / QEMU)\n");
    sh_write0("PEAKS=");         sh_print_uint((uint32_t)peaks);       sh_write0("\n");
    sh_write0("VALID_SAMPLES="); sh_print_uint((uint32_t)L);           sh_write0("\n");
    sh_write0("HR_X100=");       sh_print_uint(hr_x100);               sh_write0("\n");
    sh_write0("REF_HR_X100=");   sh_print_uint((uint32_t)REF_HR_X100); sh_write0("\n");

    sh_exit();   /* clean QEMU exit */
    return 0;
}
